### ISSUE TITLE
r.html

### ISSUE THREAD

**Issue by joelnitta** [swcarpentry-ja/2021-04-02-todai-online-ja#5]
Translation: r.html
-----

* Please translate the content into Japanese and submit the changes as a PR.
* Please assign yourself (or add a comment) to the issue **before** you start translating, so other people know that you are translating.
* Once you have finished translating, send a pull request and reference this issue.

-----
* 内容を日本語にして、翻訳をPRとして送ってください。
* あなたが翻訳し始めたと分かるように、翻訳を**始める前**にこのイシューを自分に割り振って(assign)、あるいはコメントを書いて下さい。
* 翻訳が終わったら、プルリクエストを開いて、このイシューを参照・リンクして下さい。

https://github.com/swcarpentry-ja/2021-04-02-todai-online-ja/blob/24512c032a52aab3822f955bc513ff4ead0b0999/_includes/install_instructions/r.html#L1-L65

**Comment by naganeayu** [comment]
I will work on this issue.
